import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Coole App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Hello Hummer 🦞
            <code className={styles.code}>pages/index.js</code>
          </p>
        </div>
        <Link href="/movies">Go to all Movies</Link>
        <Image
          alt="cinema impression"
          src="https://images.unsplash.com/photo-1489599849927-2ee91cede3ba"
          width={640}
          height={426}
        />
      </main>
    </>
  );
}
